# Generated by Django 3.2.6 on 2021-08-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('Взр', 'Взрослый'), ('Под', 'Подростковый'), ('Дет', 'Детский')], default='Взр', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='Ж', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование клиента')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='Информаци о клиенте')),
                ('is_debtor', models.BooleanField(default=True, null=True, verbose_name='имеет задолженность')),
                ('client_debt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PU', 'Polyurethane'), ('EVA', 'EVA')], default='PU', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Год выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(db_index=True, max_length=100, verbose_name='Код модели')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='фото')),
                ('is_available', models.BooleanField(default=True, null=True, verbose_name='в наличии')),
                ('MW', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dict.category', verbose_name='Муж_Жен')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dict.age', verbose_name='Возраст_тип')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.color', verbose_name='Цвет')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dict.material', verbose_name='Материал')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.year', verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('debt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dict.client', verbose_name='Наименование клиента')),
                ('model_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dict.product', verbose_name='Модель товара')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
