# Generated by Django 3.2.6 on 2021-08-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_type', models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='Ж', max_length=1)),
                ('shoes_type2', models.CharField(choices=[('Взр', 'Взрослый'), ('Под', 'Подростковый'), ('Дет', 'Детский')], default='Взр', max_length=3)),
                ('material', models.CharField(choices=[('PU', 'Polyurethane'), ('EVA', 'EVA')], default='PU', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(blank=True, verbose_name='Год выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=100, verbose_name='Код модели')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Контекст')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='в наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dict.category', verbose_name='Категория')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.color', verbose_name='Цвет')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.year', verbose_name='Год выпуска')),
            ],
        ),
    ]
