# Generated by Django 3.2.6 on 2021-08-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['model_code'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['id'], 'verbose_name': 'Год выпуска', 'verbose_name_plural': 'Год выпуска'},
        ),
    ]
