# Generated by Django 3.2.6 on 2021-08-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20210808_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, null=True, verbose_name='в наличии'),
        ),
    ]
