# Generated by Django 3.2.6 on 2021-08-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20210817_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_debt',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Информация о клиенте'),
        ),
    ]
