# Generated by Django 3.2.6 on 2021-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(blank=True, max_length=4, verbose_name='Год выпуска'),
        ),
    ]
