# Generated by Django 3.2.6 on 2021-08-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20210822_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
