# Generated by Django 3.2.6 on 2021-08-26 14:08

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered_date',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.date.today),
        ),
    ]
