# Generated by Django 3.2.6 on 2021-08-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_auto_20210808_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_debt',
            field=models.IntegerField(default=0),
        ),
    ]
