# Generated by Django 3.2.6 on 2021-09-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_product_delivered_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-delivered_date'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
